name: "dbt_demo"
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  dbt_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
